import { app, screen, BrowserWindow } from "electron";
import { setupIpc } from "./setupIpc";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const CONTROL_WINDOW_WEBPACK_ENTRY: string;
declare const CONTROL_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const PLAYER_WINDOW_WEBPACK_ENTRY: string;
declare const PLAYER_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const getPlayerScreenPosition = (): Electron.Rectangle => {
  const allScreens = screen.getAllDisplays();
  if (allScreens.length > 1) {
    return (
      allScreens.find(
        (screen) => screen.bounds.x !== 0 || screen.bounds.y !== 0,
      )?.bounds || allScreens[0].bounds
    );
  }
  return allScreens[0].bounds;
};

const createWindows = () => {
  const controlWindow = new BrowserWindow({
    height: 600,
    width: 800,
    darkTheme: true,
    webPreferences: {
      preload: CONTROL_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  //controlWindow.setAlwaysOnTop(true);

  controlWindow.loadURL(CONTROL_WINDOW_WEBPACK_ENTRY);

  const { x, y } = getPlayerScreenPosition();

  const playerWindow = new BrowserWindow({
    height: 600,
    width: 800,
    x,
    y,
    autoHideMenuBar: true,
    center: true,
    darkTheme: true,
    //titleBarStyle: "hidden",
    webPreferences: {
      preload: PLAYER_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  playerWindow.loadURL(PLAYER_WINDOW_WEBPACK_ENTRY);

  controlWindow.webContents.openDevTools();
  playerWindow.webContents.openDevTools();

  return { controlWindow, playerWindow };
};

app.whenReady().then(() => {
  const { controlWindow, playerWindow } = createWindows();

  setupIpc(controlWindow, playerWindow);
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
