import { app, screen, BrowserWindow } from "electron";
import { preselectDisplay } from "./preselectDisplay";
import { setupIpc } from "./setupIpc";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const CONTROL_WINDOW_WEBPACK_ENTRY: string;
declare const CONTROL_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const PLAYER_WINDOW_WEBPACK_ENTRY: string;
declare const PLAYER_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const CONTROL_WINDOW_WIDTH = 380;
const CONTROL_WINDOW_HEIGHT = 650;

const debugControl = process.argv.includes("--debug-control");
const debugPlayer = process.argv.includes("--debug-player");

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const getPlayerScreenBounds = (): Electron.Rectangle => {
  return preselectDisplay(screen.getAllDisplays()).bounds;
};

const createWindows = () => {
  const dimensions = getPlayerScreenBounds();
  const isMultiDisplay = screen.getAllDisplays().length > 1;

  const playerWindow = new BrowserWindow({
    ...dimensions,
    transparent: true,
    frame: false,
    fullscreen: true,
    alwaysOnTop: isMultiDisplay, // pin to top only on a different screen
    skipTaskbar: isMultiDisplay,
    hasShadow: true,
    title: "Dreamcatcher Player",
    webPreferences: {
      preload: PLAYER_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  playerWindow.hide();

  playerWindow.loadURL(PLAYER_WINDOW_WEBPACK_ENTRY);

  const primaryDisplay = screen.getPrimaryDisplay();

  const controlWindow = new BrowserWindow({
    height: 650,
    width: 480,
    x: primaryDisplay.bounds.x + primaryDisplay.workAreaSize.width - 480 - 20,
    y: primaryDisplay.bounds.y + primaryDisplay.workAreaSize.height - 650 - 20,
    darkTheme: true,
    backgroundColor: "#222222",
    autoHideMenuBar: true,
    webPreferences: {
      preload: CONTROL_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  controlWindow.loadURL(CONTROL_WINDOW_WEBPACK_ENTRY);

  controlWindow.on("closed", () => {
    app.quit();
  });

  if (debugControl) {
    controlWindow.webContents.openDevTools({
      mode: "detach",
      title: "Control DevTools",
    });
  }
  if (debugPlayer) {
    playerWindow.webContents.openDevTools({
      mode: "detach",
      title: "Player DevTools",
    });
  }

  return { controlWindow, playerWindow };
};

app.whenReady().then(() => {
  const { controlWindow, playerWindow } = createWindows();

  setupIpc(controlWindow, playerWindow);
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
