import { app, screen, BrowserWindow } from "electron";
import { preselectDisplay } from "./preselectDisplay";
import { setupIpc } from "./setupIpc";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const CONTROL_WINDOW_WEBPACK_ENTRY: string;
declare const CONTROL_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const PLAYER_WINDOW_WEBPACK_ENTRY: string;
declare const PLAYER_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const getPlayerScreenBounds = (): Electron.Rectangle => {
  return preselectDisplay(screen.getAllDisplays()).bounds;
};

const createWindows = () => {
  const controlWindow = new BrowserWindow({
    height: 650,
    width: 480,
    darkTheme: true,
    backgroundColor: "#222222",
    autoHideMenuBar: true,
    webPreferences: {
      preload: CONTROL_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  //controlWindow.setAlwaysOnTop(true);

  controlWindow.loadURL(CONTROL_WINDOW_WEBPACK_ENTRY);

  const dimensions = getPlayerScreenBounds();

  const playerWindow = new BrowserWindow({
    ...dimensions,
    transparent: true,
    frame: false,
    fullscreen: true,
    alwaysOnTop: true,
    hasShadow: true,
    parent: controlWindow,
    title: "Dreamcatcher Player",
    webPreferences: {
      preload: PLAYER_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  playerWindow.loadURL(PLAYER_WINDOW_WEBPACK_ENTRY);

  /*controlWindow.webContents.openDevTools({
    mode: "detach",
    title: "Control DevTools",
  });
  playerWindow.webContents.openDevTools({
    mode: "detach",
    title: "Player DevTools",
  });*/

  return { controlWindow, playerWindow };
};

app.whenReady().then(() => {
  const { controlWindow, playerWindow } = createWindows();

  setupIpc(controlWindow, playerWindow);
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
